# 纯数字需要打引号！！！
# 全局配置中的中间件配置可以配外部服务
global:
  repository: 
  # imagePullSecrets:
  #   - name: aliyun
  storageClassName: 

# 端口，健康检查默认端口
# port: 80
# extraPort:
#   - port: 8080
#     protocol: TCP
# 节点数
replicas: 1
# 重启策略
# restartPolicy: Always
# 资源类型 Deployment 或 StatefulSet
resourceType: Deployment

image:
  # 默认取chartName
  name: nginx
  # 默认取全局repository
  repository: 
  tag: latest
  # pullPolicy: IfNotPresent

# 默认策略为重新创建pod
strategy:
  type: Recreate
  # type: RollingUpdate
  # rollingUpdate:
  #   maxSurge: 25%
  #   maxUnavailable: 25%
  
# imageSecrets:
  # - name: aliyun
  #   url: registry.cn-hangzhou.aliyuncs.com
  #   username: xxxx
  #   password: xxxx

# 环境变量配置，value支持模板
# env: 
#   XXXX: aaaa

# 存在data这会自动创建配置，否则仅引用
# config:
#   - name: redis-cluster-default
#     type: ConfigMap
#     data:
#       - key: test
#         value: aaa
#   - name: service-config
#     type: Secret
#     attach: env
#     data:
#         # 日志服务ali uid
#       - key: ALI_UID
#         value: 
#         # arms的license key
#       - key: ARMS_LICENSE_KEY
#         value:
#         # 环境标识
#       - key: ENVNAME
#         value: dev
#   - name: redis-config
#     type: ConfigMap
#     attach: file
#     mountPath: /etc/redis
#     data:
#       - key: redis.conf
#         value: aaa
#   - name: rclone-config
#     type: ConfigMap
#     attach: none
#     mountPath: /etc/rclone
#     data:
#       - key: redis.conf
#         value: aaa

# 如果name为空，type为ClusterIP时，选择自定义集群端口映射。否则自动创建集群端口映射
# service:
#   - type: NodePort
#     ports:
#       - name: server
#         port: 9083
#         targetPort: 9083
#         protocol: TCP
#         # nodePort: 
#     selector:
#       aaa: bbb

# ports: 
#   - name: server
#     containerPort: 9083
#     protocol: TCP

health:
  enabled: true
  # 检查模式
  mode: tcp
  # 不健康阈值
  failureThreshold: 3
  # 健康阈值
  successThreshold: 1
  # 存活检测延迟
  livenessDelaySeconds: 10
  # 就绪检测延迟
  readinessDelaySeconds: 10
  # 检测间隔
  periodSeconds: 5
  # 检测超时
  timeoutSeconds: 5

resources: 
  limits:
    cpu: 512m
    memory: 1024Mi
  requests:
    cpu: 1m
    memory: 32Mi

# lifecycle:

# command:
# args:

# 只有emptyDir和hostPath支持mountPropagation
# volumes:
#   - name: share-path
#     mountPath: /home/app/sharedFileData
#     subPath: share-data
#     persistentVolume: 
#       # create 为true时，创建的pvc自动在前面拼接helm的名称，如果为false则不拼接
#       create: true
#       accessModes: ReadWriteMany
#       storageSize: 10Gi
#   - name: test
#     mountPath: /shared
#     mountPropagation: HostToContainer
#     emptyDir: true
#   - name: data
#     mountPath: /home/app/sharedFileData
#     mountPropagation: Bidirectional
#     hostPath: 
#       path: /home/admin
#       # DirectoryOrCreate Directory File FileOrCreate Socket CharDevice BlockDevice
#       type: DirectoryOrCreate
#   - name: config
#     mountPath: /opt/rabbitmq#     readOnly: true
#     configMap:
#       name: rabbitmq-config
#       items:
#       - key: rabbitmq.conf
#         path: rabbitmq.conf

# initContainers: []

# sidecars: []

# cloudflare tunnel
# https://github.com/adyanth/cloudflare-operator
tunnel:
  enabled: false
  hostname: xxx.monlor.com
  # tunnel ref name
  ref: monlor-com
  disableDNSUpdates: false
  noTlsVerify: false
  target: 
  protocol: 
  
ingress:
  enabled: false
  # className: traefik
  # clusterIssuer: cloudflare
  # cloudflareOnly: false
  # hosts:
  # - host: example.com

hooks:
  enabled: false
  data:
    - name: run-after
      hook: post-upgrade
      weight: 5
      deletePolicy: before-hook-creation
      image: xxxx:v0.0.1
      env:
        - name: "XXXX"
          value: "false"
      config:
        - name: service-config
          type: ConfigMap
          optional: true
        - name: service-secret
          type: Secret
          optional: true
    - name: run-before
      hook: pre-upgrade
      weight: 5
      deletePolicy: before-hook-creation
      image: xxxx:v0.0.1
      env:
        - name: "XXXX"
          value: "true"
      config:
        - name: service-config
          type: ConfigMap
          optional: true
        - name: service-secret
          type: Secret
          optional: true
        
