{{- $appName := include "helm.name" . -}}
{{- $namespace := include "helm.namespace" . -}}
{{- if .Values.ingress }}
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $appName }}
  namespace: {{ $namespace }}
  labels:
    ingress-cf-dns.k8s.io/enabled: {{ .Values.icd.enabled | quote }}
    {{- include "helm.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.ingress.clusterIssuer }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer }}
    {{- end }}
    {{- if .Values.ingress.cloudflareOnly }}
    {{- if eq .Values.ingress.className "nginx" }}
    nginx.ingress.kubernetes.io/whitelist-source-range: 173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/13,104.24.0.0/14,172.64.0.0/13,131.0.72.0/22,2400:cb00::/32,2606:4700::/32,2803:f800::/32,2405:b500::/32,2405:8100::/32,2a06:98c0::/29,2c0f:f248::/32
    {{- else if eq .Values.ingress.className "traefik" }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Values.ingress.middlewares | default "kube-system-cloudflare@kubernetescrd" }}
    {{- end }}
    {{- end }}
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ .host }}
    http:
      paths:
      - path: {{ .path | default "/" }}
        pathType: Prefix
        backend:
          service:
            name: {{ .service | default $appName }}
            port:
              number: {{ .port | default $.Values.port }}
      {{- range .paths }}
      - path: {{ .path | default '/' }}
        pathType: Prefix
        backend:
          service:
            name: {{ .service | default $appName }}
            port:
              number: {{ .port | default $.Values.port }}
      {{- end }}
  {{- end }}
  {{- if .Values.ingress.clusterIssuer }}
  tls: 
    {{- range .Values.ingress.hosts }}
    - hosts:
      - {{ .host }}
      secretName: {{ printf "%s-tls" (.host | replace "." "-") }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}