{{- $appName := include "helm.name" . -}}
{{- $namespace := include "helm.namespace" . -}}
{{- if .Values.ingress }}
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $appName }}
  namespace: {{ $namespace }}
  labels:
    ingress-cf-dns.k8s.io/enabled: {{ .Values.icd.enabled | quote }}
    {{- include "helm.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.icd.enabled }}
    ingress-cf-dns.k8s.io/proxied: {{ .Values.icd.proxied | default "true" | quote }}
    {{- end }}
    {{- if .Values.ingress.clusterIssuer }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer }}
    {{- end }}
    {{- if .Values.ingress.middlewares }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ join "," .Values.ingress.middlewares }}
    {{- end }}
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ .host }}
    http:
      paths:
      - path: {{ .path | default "/" }}
        pathType: Prefix
        backend:
          service:
            name: {{ .service | default $appName }}
            port:
              number: {{ .port | default $.Values.port }}
      {{- range .paths }}
      - path: {{ .path | default '/' }}
        pathType: Prefix
        backend:
          service:
            name: {{ .service | default $appName }}
            port:
              number: {{ .port | default $.Values.port }}
      {{- end }}
  {{- end }}
  {{- if .Values.ingress.clusterIssuer }}
  tls: 
    {{- range .Values.ingress.hosts }}
    - hosts:
      - {{ .host }}
      secretName: {{ printf "%s-tls" (.host | replace "." "-") }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}