{{- $appName := include "helm.name" . -}}
{{- $namespace := include "helm.namespace" . -}}
{{- if .Values.ingress }}
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $appName }}
  namespace: {{ $namespace }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.ingress.clusterIssuer }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer }}
    {{- end }}
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
        - path: {{ default "/" .Values.ingress.path }}
          pathType: {{ default "Prefix" .Values.ingress.type }}
          backend:
            service:
              name: {{ default $appName .Values.ingress.service }}
              port:
                number: {{ default .Values.port .Values.ingress.port }}
  {{- range .Values.ingress.paths }}
        - path: {{ default "/" .path }}
          pathType: {{ default "Prefix" .type }}
          backend:
            service:
              name: {{ default $appName .service }}
              port:
                number: {{ default $.Values.port .port }}
  {{- end }}
  {{- if .Values.ingress.secretName }}
  tls: 
    - hosts:
      - {{ .Values.ingress.hostname }}
      secretName: {{ .Values.ingress.secretName }}
  {{- end }}
{{- end }}
{{- end }}