{{- $namespace := include "helm.namespace" . -}}
{{- $selector := include "helm.labels" . -}}
{{- $appName := include "helm.name" . -}}
{{- $storageClass := include "helm.storageClass" . -}}
{{- if and .Values.volumes (eq .Values.resourceType "Deployment") -}}
{{- range .Values.volumes }}
{{- if .persistentVolume }}
{{- if .persistentVolume.create }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-%s" $appName .name }}
  namespace: {{ $namespace }}
  labels:
  {{- $selector | nindent 6 }}
spec:
  accessModes:
  - {{ .persistentVolume.accessModes }}
  resources:
    requests:
      storage: {{ .persistentVolume.storageSize }}
  {{- if $storageClass }}
  storageClassName: {{ $storageClass }}
  {{- end }}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}