{{- $labels := include "helm.labels" . -}}
{{- $name := include "helm.serviceAccountName" . -}}
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  labels:
    {{- $labels | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}

{{- range .Values.serviceAccount.roles }}
---
{{- if .cluster }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
{{- end }}
metadata:
  name: {{ coalesce .name $name }}
  labels:
    {{- $labels | nindent 4 }}
rules:
  {{- toYaml .rules | nindent 2 }}
---
{{- if .cluster }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
{{- end }}
metadata:
  name: {{ coalesce .name $name }}
  labels:
    {{- $labels | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ $name }}
  namespace: {{ $.Release.Namespace }}
roleRef:
  {{- if .cluster }}
  kind: ClusterRole
  {{- else }}
  kind: Role
  {{- end }}
  name: {{ coalesce .name $name }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }} 