{{- if .Values.headscale.derp.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: headscale-derp-config
  labels:
    app: headplane
data:
  derp.yaml: |
{{ .Values.headscale.derp.config | nindent 4 }}
{{- end }} 