apiVersion: v2
appVersion: 0.5.5
description: The headplane Helm chart provides an easy way to deploy a Headscale UI
  with headplane, including an embedded Tailscale relay. This chart simplifies the
  setup of a private networking solution using Kubernetes.
name: headplane
type: application
version: 0.1.1
