name: diun
replicaCount: 1

image:
  repository: crazymax/diun
  tag: latest
  pullPolicy: Always

env:
  TZ: "Asia/Shanghai"
  LOG_LEVEL: "info"
  LOG_JSON: "false"
  DIUN_WATCH_WORKERS: "20"
  DIUN_WATCH_SCHEDULE: "0 */6 * * *"
  DIUN_WATCH_JITTER: "30s"
  DIUN_PROVIDERS_KUBERNETES: "true"

persistence:
  enabled: true
  ## 如果设置了existingClaim，将使用已存在的PVC
  # existingClaim: ""
  accessMode: ReadWriteOnce
  size: 128Mi
  storageClass: ""